version: '3'

services:
  # RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bigsofa-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - "RABBITMQ_DEFAULT_PASS=pass"
      - "RABBITMQ_DEFAULT_USER=user"
    networks:
      platform:
        aliases:
          - torii-rabbitmq

  # TORII
  bigsofa-torii:
    build: .
    container_name: bigsofa-torii
    ports:
      - "3006:3000"
    environment:
      - QUEUE_HOST=torii-rabbitmq
      - USER=user
      - PASS=pass
    depends_on:
      - rabbitmq
    networks:
      platform:
        aliases:
          - torii-rails

networks:
  platform:
    external:
      name: platform
