version: 2.1

executors:
  torii-executor:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo

jobs:
  build:
    executor: torii-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Build container and Release
          # Change it to use credentials from configuration once our account is updated
          command: source build.sh $CIRCLE_BRANCH

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
